#FROM alpine:3.16
FROM alpine:latest

RUN apk update \
    && apk upgrade \
    && apk add curl \
               openssl \
               openssl-dev \
               gcc \
               make \
               perl \
               perl-app-cpanminus \
               #
               perl-b-cow \
               perl-clone \
               perl-http-message \
               perl-http-cookies \
               perl-http-daemon \
               perl-http-negotiate \
               perl-libwww \
               perl-lwp-protocol-https \
               #
                perl-par \
                perl-par-packer \
               #
               perl-date-calc \
               perl-json \
               perl-json-maybexs \
               perl-getopt-long \
               perl-image-exiftool \
    && rm -rf /var/cache/apk/* \
    #
    && /usr/bin/cpanm LWP::UserAgent \
                      File::Copy \
                      URI::Heuristic \
                      HTTP::Request \
   && rm -rf /root/.cpanm/*
#
RUN mkdir -p /app/scripts && \
    mkdir -p /app/conf && \
    mkdir -p /app/data && \
    mkdir -p /app/external
#
ADD https://github.com/lveatch/immich-migrate-tools/raw/refs/heads/main/assets/docker/export.albums /app/scripts
ADD https://github.com/lveatch/immich-migrate-tools/raw/refs/heads/main/assets/docker/export.asset.info.2.xmp /app/scripts
ADD https://github.com/lveatch/immich-migrate-tools/raw/refs/heads/main/assets/docker/export.people /app/scripts
ADD https://github.com/lveatch/immich-migrate-tools/raw/refs/heads/main/assets/docker/import.albums /app/scripts
ADD https://github.com/lveatch/immich-migrate-tools/raw/refs/heads/main/assets/docker/import.people /app/scripts
#
ENV TZ=America/New_York
ENV PATH="/app/scripts:$PATH"
ENV container=docker.alpine
RUN chmod 550 /app/scripts/*
RUN chown 1000 /app/scripts/*
#
USER 1000
#


