#FROM alpine:3.16
FROM alpine:latest

RUN apk update \
    && apk upgrade \
    && apk add curl \
               openssl \
               openssl-dev \
                perl-par \
                perl-par-packer \
    && rm -rf /var/cache/apk/* 
#
RUN mkdir -p /app/scripts && \
    mkdir -p /app/conf && \
    mkdir -p /app/data && \
    mkdir -p /app/external
#
ADD https://github.com/lveatch/immich-migrate-tools/raw/refs/heads/main/assets/docker/export.albums /app/scripts
ADD https://github.com/lveatch/immich-migrate-tools/raw/refs/heads/main/assets/docker/import.albums /app/scripts
#
ADD https://github.com/lveatch/immich-migrate-tools/raw/refs/heads/main/assets/docker/export.people /app/scripts
ADD https://github.com/lveatch/immich-migrate-tools/raw/refs/heads/main/assets/docker/import.people /app/scripts
#
ADD https://github.com/lveatch/immich-migrate-tools/raw/refs/heads/main/assets/docker/export.asset.info.2.xmp /app/scripts
#
ADD https://github.com/lveatch/immich-migrate-tools/raw/refs/heads/main/assets/docker/export.assets /app/scripts
#
ENV TZ=America/New_York
ENV PATH="/app/scripts:$PATH"
ENV container=docker.alpine
RUN chmod 550 /app/scripts/*
RUN chown 1000 /app/scripts/*
#
USER 1000
#


